### PR TITLE
Tbaker

### PR DESCRIPTION
**Pull request by TiffersAnn**
# Description

From tbaker branch, run code, Main Menu appears. Choose Blog Management option 2.

Ticket #11 - from Blog Management, option 3-Add Blog - Inputs Title & Url. It is saved in database and now shows up when List Blogs is selected. 
Ticket#12 - from Blog Management option 1- List Blogs - just a list of Blog titles to read appears
Ticket #13 - from Blog Management option 5- Remove Blog - a list of blogs with # options appear. When Blog # is selected, that blog disappears from the database. 
Ticket#14 - from Blog Management option  4-Edit Blog - a list of blogs with # options appear. When Blog # is selected, you can change the Title or Url. If no change is necessary, hit enter and nothing will change, otherwise all changes will save in the database. 

Ticket#25 - From Blog Management, option 2-Blog Details - a list of blogs with # options appear. When Blog # is selected, you can View details by choosing option 1.  Name of blog and any added Tags of blog will appear.  

--BlogManager.cs was added.
-- I added a return Blog Manager to MainMenuManager

# Testing Instructions

tbaker is the branch

Blog added---
Title: Happenchance
Url: https://www.happenchance.net/about/

Make your instructions ***explicit***.
State which branch, link any seed data, any data they need to enter to have the feature perform correctly, step by step of exactly what they should see

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jacobjjude** [comment]
BlogRepository.cs
Line 128, chance "@firstName" to "@title" in order to update title.

BlogManager.cs
Lines 131 + 137, add closing brackets to WriteLines.

**Comment by julslt34** [comment]
BlogRepository.cs
Line 128, chance "@firstname" to "@title" in order to update title.
Line 129, chance "@firstname" to "@url" in order to update title.

BlogManager.cs
Lines 131 + 137, add closing brackets to WriteLines.

**Comment by jacobjjude** [comment]
🌟 Great job! Works as described.

**Review by jacobjjude — APPROVED** [review]
🌟

**Comment by julslt34** [comment]
Looks great!

**Review by julslt34 — APPROVED** [review]
Works as described!

**Pull request merged**
