### PR TITLE
Tag edit remove

### PR DESCRIPTION
**Pull request by TiffersAnn**
Tickets 22 & 23  

Original Seed Data:
https://github.com/NewForce-Cohort-6/tabloid-cli-coven-of-the-twilight-knowledge/blob/main/TabloidCLI.sql

https://trello.com/c/efzK3IN7
https://trello.com/c/Ni3s3rF2
You can now edit and remove Tags that have been previously created. 

TagRepository: Update() and Delete()

**Also... the fix to Add and Edit Post was changed in PostManager.  Foreach switched to For loop. Numbers for Author and Blogs are now correct and not out of range. 

# Testing Instructions
Edit Tag:
From Branch TagEditRemove start code and you will see Main Menu.  Choose option 5 - Tag Management.
Select option 3 - Edit Tag.
You will see a list of previously added Tags with # options.  Select the Tag you wish to edit.
You can enter a new Tag name or press enter to leave unchanged. 
New Tag name will be altered in database if you typed in a new name. 

Remove Tag:
From Branch TagEditRemove start code and you will see Main Menu.  Choose option 5 - Tag Management.
Select option 4 - Remove Tag.
You will see a list of previously added Tags with # options.  Select the Tag you wish to delete.
The selected Tag name will be removed from database and no longer show up in Tag List. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jacobjjude — CHANGES_REQUESTED** [review]
Tags do not delete if tag is attached to an Author/Post/Blog.

**Review by julslt34 — CHANGES_REQUESTED** [review]
Edit Tag works as it is supposed to.  Remove tag will not work if tag is tied to an author

**Review by jacobjjude — APPROVED** [review]
🌟

**Review by julslt34 — APPROVED** [review]
Looks Good!

**Pull request merged**
